### ISSUE TITLE
LGButton's gradients or background color does not change

### ISSUE THREAD

**Issue by idevChandra6** [loregr/LGButton#68]
**Describe the bug**
Depending on a flag, I want to change the gradient colors (Or, background color) of an LGButton. But, we cannot change the colors runtime from whatever the colors the button is initially initiated with or given on storyboard.

**To Reproduce**
1. Drag an `UIView` onto any `UIViewController`'s `UIView` or another `UIView`. 
2. Make it an instance of `LGButton` and assign an `IBOutlet`
3. Assign them two gradient colors or just background color.
4. Have a piece of code something like shown below to have new gradient colors.
5. Check if new gradients are applied to the `lgButton`.
```
if status == true {
    lgButton.gradientStartColor = .red
    lgButton.gradientEndColor = .green
} else {
    lgButton.gradientStartColor = .gray
    lgButton.gradientEndColor = .white
}

```

**Smartphone (please complete the following information):**
iOS 12, 11

**Comment by idevChandra6** [comment]
Does anyone have any inputs?

**Comment by aryobarzan** [comment]
I've noticed the same problem, though I've found a way to change the gradient colors during runtime by firstly setting both gradients to nil and changing the horizontal gradient orientation to false.
```
lgButton.gradientEndColor = nil
lgButton.gradientStartColor = nil
lgButton.gradientHorizontal = false
lgButton.gradientStartColor = UIColor(red: 95.0/255.0, green: 193.0/255.0, blue: 148.0/255.0, alpha: 1)
lgButton.gradientEndColor = UIColor(red: 0.0, green: 122.0/255.0, blue: 255.0/255.0, alpha: 1)
```

This trick does not work for me to change the background color during runtime however.

edit: I was wrong with my last point, you can change the background color during runtime! I was trying to change the 'backgroundColor' property instead of the correct 'bgColor' property.

**Comment by pmrzygweb** [comment]
@idevChandra6 I experienced same bug and setting gradientHorizontal property fixed the issue
