### ISSUE TITLE
Title font weight

### ISSUE THREAD

**Issue by mayforth** [loregr/LGButton#9]
Is there any way I can set the font weight of the title text?

**Comment by loregr** [comment]
Hi @mayforth if you want to use the system font with different weights you can achieve that by using the different styles of the `HelveticaNeue` font in the `Title Font Name` property. So you should write `HelveticaNeue-Bold`, `HelveticaNeue-Medium`, `HelveticaNeue-Italic`, and so on.

Let me know if this solve your issue. Thanks

**Comment by mayforth** [comment]
Sorry, I was just not aware of this approach :) Yes, it works.

**Comment by loregr** [comment]
I'm glad to hear that :-). I'm closing the issue then.

**Comment by emarthinsen** [comment]
@loregr Quick related question on this. Since iOS 9, the system font has been San Francisco. Just like the poster, I'm trying to change the font weight. Apparently, the string `.SFUIText-Medium` can be used to reference the medium weight of the system font. However, Apple specifically says that this is unsafe, since the system font could change at any time. Is there any way to break out a separate weight configuration field or to accept a font name like `System-Medium`?

**Comment by loregr** [comment]
@emarthinsen right now there's no way to change the default system font weight. But this can be easily implemented by adding to LGButton a new property `FontWeight` that will be considered only if the the `FontName` property is empty. I'll try to push it as soon as I'll have some spare time. Thanks :-)
